config/routes.rb
Rails.application.routes.draw do
  # ROUTES

  # ROOT
  root "home#top"

  # ABOUT
  get "home/about"

  # RESOURCES
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "users/:id" => "users#show", as: :mypage
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # ASSOCIATIONS
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # FAVORITED METHOD
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # VARIDATIONS
  validates :title,
            presence: true
  validates :body,
            presence: true,
            length: { minimum: 0, maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  # ASSOCIATIONS
  belongs_to :user
  belongs_to :book

  # VARIDATIONS
  validates :comment,
            presence: true,
            length: { minimum: 0, maximum: 200 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # ASSOCIATIONS
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ASSOCIATIONS
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # REFILE ATTACHMENT
  attachment :profile_image

  # Adds: except email from devise
  # COMMENT OUT V
  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end
  # COMMENT OUT ^

  # VARIDATIONS

  validates :name,
    uniqueness: true,
    presence: true,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
            length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # --- Adds: name to devise ------
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Signin Singup Redirects
  def after_sign_in_path_for(resource)
    mypage_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    # Adds: name
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  #--------------------------------
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.find(params[:book_comment_id])
    if comment.user.id == current_user.id
      comment.destroy
    end
    redirect_back(fallback_location: book_path(book))
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:user_id, :book_id, :comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # Adds: reject not-signin users
  before_action :authenticate_user!

  # Adds: reject not-edit another user prifiles
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all.order(created_at: :desc)
    # LEFT CONTENT
    @book_new = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    
    # LEFT CONTENT
    @user = current_user
    @book_new = Book.new
    
    # COMMENT
    # @book_comment = @book.book_comments.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    # Another Syntax
    # book = current_user.book.new(book_params_params)
    #
    # commentout
    # book.save
    # redirect_to books_path
    #
    if @book_new.save
      redirect_to book_path(@book_new), notice: "You have creatad book successfully."
    else
      @books = Book.all.order(created_at: :desc)
      @user = current_user # left content
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def correct_user
    book = Book.find(params[:id])
    # refactering because book model has belong_to
    if current_user.id != book.user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Adds: reject not-signin users
  before_action :authenticate_user!

  # Adds: reject not-edit another user prifiles
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all.order(created_at: :desc)
    @book_new = Book.new # left content
    @user = current_user # left content
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new # left content
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # Update Validations
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updatad user successfully."
    else
      render :edit
    end
  end

  private

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<%# BOOK VALIDATION %>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%#  %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_for(@book) do |f| %>
      <div class="field row">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"col-xs-12 book_title" %>
      </div>
      <div class="field row">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"col-xs-12 book_body" %>
      </div>
      <div class="actions row">
        <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
      </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %> |
    <%= link_to "Back", books_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<%# BOOKS INDEX %>
<p id="notice"></p>
<%# BOOK VALIDATION %>
<% if @book_new.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @book_new.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%#  %>
<div class='row'>
  <%# ↓ INSERT LEFT CONTENTS %>
  <%= render 'users/left_contents', book_new: @book_new, user: @user%>
  <%# ↑ INSERT LEFT CONTENTS END %>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <i class="fa fa-comment"></i>
              <a href="#comments"><%= book.book_comments.count %></a>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/books/show.html.erb
<%# BOOKS SHOW --- DETAILS %>
<p id="notice"></p>
<div class='row'>
  <%# ↓ INSERT LEFT CONTENTS %>
  <%= render 'users/left_contents', book_new: @book_new, user: @book.user%>
  <%# ↑ INSERT LEFT CONTENTS END %>
  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle attachment user profile_image fallback", fallback: "no_image.jpg" %>
              <%= link_to @book.user.name, user_path(@book.user), style:"margin-left:10px;" %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <td>
            <i class="fa fa-comment"></i>
            <a href="#comments"><%= @book.book_comments.count %></a>
          </td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= @book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= @book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class:'btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class:'btn-sm btn-danger', "data-confirm" => "Are you sure?" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
    <h3>Comments</h3>
    <div class="col-xs-8 col-xs-offset-2">
      <h4 class="comment-count"><%= @book.book_comments.count %> comments</h4>
      <%# COMMENT EACH %>
      <% @book.book_comments.each do |book_comment| %>
        <table class="table">
          <tr>
            <td>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 30, 30, format: 'jpeg', class: "img-circle attachment user profile_image fallback", fallback: "no_image.jpg" %>
            </td>
            <td>
              <a href="#" class="link-author"><%= book_comment.user.name%></a>
            </td>
            <td>
              <div class="comment-entry"><%= book_comment.comment %></div>
            </td>
            <td>
              <span class="comment-meta">
                <span class="comment-date"><%= book_comment.created_at.strftime('%Y.%m.%d')%></span>
              </span>
            </td>
            <% if book_comment.user == current_user %>
              <td><%= link_to "Destroy", book_book_comments_path(book_id: book_comment.book.id, book_comment_id: book_comment), method: :delete, class:'btn-sm btn-danger', "data-confirm" => "Are you sure?" %></td>
            <% end %>
          </tr>
        </table>
      <% end %>
      <%# COMMENT FORM %>
      <%= form_for [@book, @book_comment] do |f| %>
        <div class="row">
          <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "Comment" %>
          </div>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
    <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div class="btn-wrapper">
      <% if user_signed_in? %>
        <div class="row">
          <p><%=link_to "Log in", user_path(current_user), class: "btn btn-info col-xs-10 col-xs-offset-1"%></p>
        </div>
        <div class="row">
          <p><%=link_to "Sign Up", user_path(current_user), class: "btn btn-success col-xs-10 col-xs-offset-1"%></p>
        </div>
      <% else %>
        <div class="row">
          <p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1"%></p>
        </div>
        <div class="row">
          <p><%=link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1"%></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Adds: Font Awesome %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="body">
      <%# Header %>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <span class="title" >Bookers</span>
          </nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <%# sign in %>
                <li><%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %></li>
                <li><%= link_to "Users", users_path, class:"glyphicon glyphicon-user users" %></li>
                <li><%= link_to "Books", books_path, class:"glyphicon glyphicon-book books" %></li>
                <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out logout" %></li>
              <% else %>
                <%# sign out %>
                <li><%= link_to "Home", root_path, class:"glyphicon glyphicon-home home" %></li>
                <li><%= link_to "About", home_about_path, class:"glyphicon glyphicon-link about" %></li>
                <li><%= link_to "Sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %></li>
                <li><%= link_to "login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
      <div class="container">
        <%# Notice %>
        <% if flash[:notice] %>
          <p id="notice"><%= flash[:notice] %></p>
        <% end %>
        <%# yield %>
        <%= yield %>
      </div>
      <%# Footer %>
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-2 col-xs-offset-10">
              <p>© 2019 Infratop, Inc.</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/users/_left_contents.html.erb
<%# _LEFT_CONTENTS %>
<div class="col-xs-3">
<%# USER INFO %>
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%# EDIT USER BUTTON%>
  <% if user.id == current_user.id %>
    <div class="row">
      <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>
  <% end %>
  <%# NEW BOOK %>
  <h2>New book</h2>
  <%= form_for(book_new) do |f| %>
    <div class="field row">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:'col-xs-12 book_title' %>
    </div>
    <div class="field row">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:'col-xs-12 book_body' %>
    </div>
    <div class="actions row">
      <%= f.submit 'Create Book', class:'btn btn-primary col-xs-12' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<%# USER VALIDATION %>
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
  <h2><%= @user.errors.count %> errors prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%#  %>
<%= form_for(@user) do |f| %>
  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name, autofocus: true, class:"name", placeholder:"name"%>
  </div>
  <div class="field">
    <label for="user_image">Image</label>
    <%= f.attachment_field :profile_image, placeholder: "Profile Image", class: "user-edit-form" %>
  </div>
  <div class="field">
    <label for="user_introduction">Introduction</label>
    <%= f.text_area :introduction, class:"user_body introduction", id:"user_introduction" %>
  </div>
  <div class="actions">
    <%= f.submit "Update User", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <%# ↓ INSERT LEFT CONTENTS %>
  <%= render 'users/left_contents', book_new: @book_new, user: @user%>
  <%# ↑ INSERT LEFT CONTENTS END %>
  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle attachment user profile_image", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<%# USERS SHOW %>
<div class="row">
  <%# ↓ INSERT LEFT CONTENTS %>
  <%= render 'users/left_contents', book_new: @book_new, user: @user%>
  <%# ↑ INSERT LEFT CONTENTS END %>
  <%# RIGHT CONTENTS %>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <i class="fa fa-comment"></i>
              <a href="#comments"><%= book.book_comments.count %></a>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>